/** Tesseract language models available to Scribe.js. Codes are the values
 * expected by `ScribeDoc.recognize({ langs })`. */
export const OCR_LANGUAGES = [
  ['afr', 'Afrikaans'],
  ['sqi', 'Albanian'],
  ['amh', 'Amharic'],
  ['ara', 'Arabic'],
  ['hye', 'Armenian'],
  ['asm', 'Assamese'],
  ['aze', 'Azerbaijani'],
  ['aze_cyrl', 'Azerbaijani — Cyrillic'],
  ['eus', 'Basque'],
  ['bel', 'Belarusian'],
  ['ben', 'Bengali'],
  ['bos', 'Bosnian'],
  ['bre', 'Breton'],
  ['bul', 'Bulgarian'],
  ['mya', 'Burmese'],
  ['cat', 'Catalan'],
  ['ceb', 'Cebuano'],
  ['chr', 'Cherokee'],
  ['chi_sim', 'Chinese — Simplified'],
  ['chi_tra', 'Chinese — Traditional'],
  ['cos', 'Corsican'],
  ['hrv', 'Croatian'],
  ['ces', 'Czech'],
  ['dan', 'Danish'],
  ['div', 'Dhivehi'],
  ['nld', 'Dutch / Flemish'],
  ['dzo', 'Dzongkha'],
  ['eng', 'English'],
  ['epo', 'Esperanto'],
  ['est', 'Estonian'],
  ['fao', 'Faroese'],
  ['fil', 'Filipino'],
  ['fin', 'Finnish'],
  ['fra', 'French'],
  ['fry', 'Frisian'],
  ['glg', 'Galician'],
  ['kat', 'Georgian'],
  ['deu', 'German'],
  ['ell', 'Greek'],
  ['guj', 'Gujarati'],
  ['hat', 'Haitian Creole'],
  ['heb', 'Hebrew'],
  ['hin', 'Hindi'],
  ['hun', 'Hungarian'],
  ['isl', 'Icelandic'],
  ['iku', 'Inuktitut'],
  ['ind', 'Indonesian'],
  ['gle', 'Irish'],
  ['ita', 'Italian'],
  ['jpn', 'Japanese'],
  ['jav', 'Javanese'],
  ['kan', 'Kannada'],
  ['kaz', 'Kazakh'],
  ['khm', 'Khmer'],
  ['kor', 'Korean'],
  ['kmr', 'Kurdish — Kurmanji'],
  ['kir', 'Kyrgyz'],
  ['lao', 'Lao'],
  ['lat', 'Latin'],
  ['lav', 'Latvian'],
  ['lit', 'Lithuanian'],
  ['ltz', 'Luxembourgish'],
  ['mkd', 'Macedonian'],
  ['msa', 'Malay'],
  ['mal', 'Malayalam'],
  ['mri', 'Maori'],
  ['mar', 'Marathi'],
  ['mon', 'Mongolian'],
  ['nep', 'Nepali'],
  ['nor', 'Norwegian'],
  ['oci', 'Occitan'],
  ['ori', 'Oriya'],
  ['pus', 'Pashto'],
  ['fas', 'Persian'],
  ['pol', 'Polish'],
  ['por', 'Portuguese'],
  ['pan', 'Punjabi'],
  ['que', 'Quechua'],
  ['ron', 'Romanian'],
  ['rus', 'Russian'],
  ['san', 'Sanskrit'],
  ['gla', 'Scottish Gaelic'],
  ['srp', 'Serbian'],
  ['srp_latn', 'Serbian — Latin'],
  ['snd', 'Sindhi'],
  ['sin', 'Sinhala'],
  ['slk', 'Slovak'],
  ['slv', 'Slovenian'],
  ['spa', 'Spanish'],
  ['sun', 'Sundanese'],
  ['swa', 'Swahili'],
  ['swe', 'Swedish'],
  ['syr', 'Syriac'],
  ['tgk', 'Tajik'],
  ['tam', 'Tamil'],
  ['tat', 'Tatar'],
  ['tel', 'Telugu'],
  ['tha', 'Thai'],
  ['bod', 'Tibetan'],
  ['tir', 'Tigrinya'],
  ['ton', 'Tonga'],
  ['tur', 'Turkish'],
  ['uig', 'Uyghur'],
  ['ukr', 'Ukrainian'],
  ['urd', 'Urdu'],
  ['uzb', 'Uzbek'],
  ['uzb_cyrl', 'Uzbek — Cyrillic'],
  ['vie', 'Vietnamese'],
  ['cym', 'Welsh'],
  ['yid', 'Yiddish'],
  ['yor', 'Yoruba'],
] as const;

export type OcrLanguageCode = typeof OCR_LANGUAGES[number][0];

export const DEFAULT_OCR_LANGUAGES: OcrLanguageCode[] = ['eng', 'fra', 'rus'];

const LANGUAGE_CODES = new Set<string>(OCR_LANGUAGES.map(([code]) => code));

export const isOcrLanguageCode = (value: unknown): value is OcrLanguageCode =>
  typeof value === 'string' && LANGUAGE_CODES.has(value);

export const ocrLanguageName = (code: string): string =>
  OCR_LANGUAGES.find(([candidate]) => candidate === code)?.[1] ?? code;
